name: update
on: workflow_dispatch
run-name: update-${{ github.ref }}
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        PATH_TO_NDK="$ANDROID_NDK"
        "$PATH_TO_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang" -shared -o libc.so libcrt_compat.c __aeabi.c exidx_dynamic.c -Wl,-soname=libc.so -ldl -nostdlib "$(echo "$PATH_TO_NDK/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/"*)/lib/linux/libclang_rt.builtins-arm-android.a"
        "$PATH_TO_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang" -shared -o libm.so -Wl,-soname=libm.so -Wl,--whole-archive "$PATH_TO_NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/libm.a" -Wl,--no-whole-archive
      working-directory: lib/armeabi-v7a
    - uses: actions/upload-artifact@v3
      with:
        path: |
          lib/armeabi-v7a/libc.so
          lib/armeabi-v7a/libm.so
    - name: Push
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update prebuild armhf libs"
          git push
